# _config.yml
title: Your Blog Title
description: Your blog description
baseurl: ""
url: "https://4nif.github.io"

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Header pages
header_pages:
  - about.md
  - categories.md

# Collections
collections:
  category:
    output: true
    permalink: /category/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: category
  - scope:
      path: ""
      type: posts
    values:
      layout: post